### ISSUE TITLE
About the train model of ASM

### ISSUE THREAD

**Issue by kevinoop0** [RoyalVane/ASM#2]
Hi, I have a question. I hope to get your answer.
When you train the segmentation model, you add a new module (self.PAM = PAM_Module(2048)) in Res_Deeplab model. Why not just train on the original Res_Deeplab model? You didn't do ablation experiments in your paper. How much would your method improve (mIOU) if you trained directly on the original Res_Deeplab model?

**Comment by RoyalVane** [comment]
Thank you for your question. We have conducted the related experiment w/o the non-local module in Res_Deeplab and get the mIoU around 44.0. Although the non-local function already seems a common module in many current methods, you might try to train the ASM with the ASM_G_ori.py if you want to check.

**Comment by kevinoop0** [comment]
Thanks for your answer. I used your first model to evaluate the cityscapes val dataset (500 images). The mIOU = 43.75. I just modify the directory of your code. Do you upload the wrong model?

**Comment by RoyalVane** [comment]
Really? I'll check it then.  How about the second one? Is the reported result correct?
