### ISSUE TITLE
Error Happened While Running train.py in RAIN

### ISSUE THREAD

**Issue by feipanir** [RoyalVane/ASM#6]
Hi author, thanks for sharing the code. 
While I was running your code for training RAIN module, I got such a error:

**Traceback (most recent call last):
  File "train.py", line 182, in <module>
    loss_de.backward()
  File "/home/fei/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/fei/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1024, 1024]], which is output 0 of TBackward, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
  0%|                                                                | 0/160000 [00:16<?, ?it/s]**

and I was wondering if this error happens to you either.

Regards,

**Comment by RoyalVane** [comment]
Hi, feipan, we have pinpointed this issue which is due to the pytorch version. Please use an earlier version, e.g., PyTorch 1.3.0, to run this code.

**Comment by feipanir** [comment]
sincerely appreciate your help and it successfully solved the issue. But while training the script `ASM_train.py` I got nan for both loss_seg and loss_adv, which looks like:

**.....
exp = ./snapshots/GTA2Cityscapes
iter =  10603/100000, loss_seg = nan loss_adv = nan
exp = ./snapshots/GTA2Cityscapes
iter =  10603/100000, loss_seg = nan loss_adv = nan
exp = ./snapshots/GTA2Cityscapes
iter =  10604/100000, loss_seg = nan loss_adv = nan
exp = ./snapshots/GTA2Cityscapes
iter =  10604/100000, loss_seg = nan loss_adv = nan
exp = ./snapshots/GTA2Cityscapes
iter =  10605/100000, loss_seg = nan loss_adv = nan
exp = ./snapshots/GTA2Cityscapes
iter =  10605/100000, loss_seg = nan loss_adv = nan
exp = ./snapshots/GTA2Cityscapes
iter =  10606/100000, loss_seg = nan loss_adv = nan
exp = ./snapshots/GTA2Cityscapes
iter =  10606/100000, loss_seg = nan loss_adv = nan
exp = ./snapshots/GTA2Cityscapes
iter =  10607/100000, loss_seg = nan loss_adv = nan
exp = ./snapshots/GTA2Cityscapes
iter =  10607/100000, loss_seg = nan loss_adv = nan
exp = ./snapshots/GTA2Cityscapes
iter =  10608/100000, loss_seg = nan loss_adv = nan
^CTraceback (most recent call last):**

Do you know why it causes such a case?

Sincerely,

**Comment by RoyalVane** [comment]
I am sorry that we have not encountered such issues. We used PyTorch = 1.3.0 and GPU = V100 32GB to train our model.
